services:
  frontend:
    image: wutipong/mangaweb3-frontend:latest
    environment: 
      BACKEND_URL: http://backend:8972/
      DEFAULT_SORT_FIELD:
      DEFAULT_ORDER:
    
  backend:
    image: wutipong/mangaweb3-backend:latest
    environment:
      MANGAWEB_DB:
      MANGAWEB_DATA_PATH: /data
      MANGAWEB_CACHE_PATH: /cache
    volumes:
      - ${DATA_PATH}:/data:ro
      - backend_cache:/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  caddy:
    image: caddy:alpine
    # restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  backend_cache:
  caddy_data:
  caddy_config: