services:
  frontend:
    image: wutipong/mangaweb4-frontend:latest
    restart: unless-stopped
    env_file: prod.env

  backend:
    image: wutipong/mangaweb4-backend:latest
    restart: unless-stopped
    env_file: prod.env
    volumes:
      - ${DATA_PATH-./data}:/data:ro
      - backend_cache:/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${HTTP_PORT-8000}:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  backend_cache:
  caddy_data:
  caddy_config:
